# Site settings
title: Arco Minero del Orinoco
header-img: img/home-bg.jpg
email: arcominero@protonmail.com
copyright_name: Your/Project/Corporate Name
description: "Información acerca de la explotación el Arco Minero del Orinoco"
baseurl: ""
url: ""
twitter_username: arcominero
github_username:  arcominero
email_username:  arcominero@protonmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
